export const browserCoreExamples = [
  "openaeon browser status",
  "openaeon browser start",
  "openaeon browser stop",
  "openaeon browser tabs",
  "openaeon browser open https://example.com",
  "openaeon browser focus abcd1234",
  "openaeon browser close abcd1234",
  "openaeon browser screenshot",
  "openaeon browser screenshot --full-page",
  "openaeon browser screenshot --ref 12",
  "openaeon browser snapshot",
  "openaeon browser snapshot --format aria --limit 200",
  "openaeon browser snapshot --efficient",
  "openaeon browser snapshot --labels",
];

export const browserActionExamples = [
  "openaeon browser navigate https://example.com",
  "openaeon browser resize 1280 720",
  "openaeon browser click 12 --double",
  'openaeon browser type 23 "hello" --submit',
  "openaeon browser press Enter",
  "openaeon browser hover 44",
  "openaeon browser drag 10 11",
  "openaeon browser select 9 OptionA OptionB",
  "openaeon browser upload /tmp/openaeon/uploads/file.pdf",
  'openaeon browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "openaeon browser dialog --accept",
  'openaeon browser wait --text "Done"',
  "openaeon browser evaluate --fn '(el) => el.textContent' --ref 7",
  "openaeon browser console --level error",
  "openaeon browser pdf",
];
