#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGE_NAME="${OPENAEON_INSTALL_E2E_IMAGE:-${AEONPROPHET_INSTALL_E2E_IMAGE:-openaeon-install-e2e:local}}"
INSTALL_URL="${OPENAEON_INSTALL_URL:-${AEONPROPHET_INSTALL_URL:-https://openaeon.bot/install.sh}}"

OPENAI_API_KEY="${OPENAI_API_KEY:-}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
ANTHROPIC_API_TOKEN="${ANTHROPIC_API_TOKEN:-}"
OPENAEON_E2E_MODELS="${OPENAEON_E2E_MODELS:-${AEONPROPHET_E2E_MODELS:-}}"

echo "==> Build image: $IMAGE_NAME"
docker build \
  -t "$IMAGE_NAME" \
  -f "$ROOT_DIR/scripts/docker/install-sh-e2e/Dockerfile" \
  "$ROOT_DIR/scripts/docker/install-sh-e2e"

echo "==> Run E2E installer test"
docker run --rm \
  -e OPENAEON_INSTALL_URL="$INSTALL_URL" \
  -e OPENAEON_INSTALL_TAG="${OPENAEON_INSTALL_TAG:-${AEONPROPHET_INSTALL_TAG:-latest}}" \
  -e OPENAEON_E2E_MODELS="$OPENAEON_E2E_MODELS" \
  -e OPENAEON_INSTALL_E2E_PREVIOUS="${OPENAEON_INSTALL_E2E_PREVIOUS:-${AEONPROPHET_INSTALL_E2E_PREVIOUS:-}}" \
  -e OPENAEON_INSTALL_E2E_SKIP_PREVIOUS="${OPENAEON_INSTALL_E2E_SKIP_PREVIOUS:-${AEONPROPHET_INSTALL_E2E_SKIP_PREVIOUS:-0}}" \
  -e OPENAI_API_KEY="$OPENAI_API_KEY" \
  -e ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" \
  -e ANTHROPIC_API_TOKEN="$ANTHROPIC_API_TOKEN" \
  "$IMAGE_NAME"
